// Seconde vague de contenus manuels, alignée sur les attendus scolaires du CP au CM2.
// Chaque entrée contient : question, bonne réponse, deux distracteurs.
export const CURRICULUM_QUESTION_FACTS = {
  anglais: {
    1: [
      ["🇬🇧 Que veut dire « Good morning » ?", "Bonjour le matin", "Bonne nuit", "À demain"],
      ["🇬🇧 Quel mot signifie « frère » ?", "brother", "sister", "mother"],
      ["🇬🇧 Que veut dire « Open your book » ?", "Ouvre ton livre", "Ferme la porte", "Prends ton manteau"],
      ["🇬🇧 Quel mot signifie « main » ?", "hand", "head", "foot"],
      ["🇬🇧 Que veut dire « sunny » ?", "ensoleillé", "pluvieux", "nuageux"],
      ["🇬🇧 Complète : My name ___ Lina.", "is", "are", "am"],
      ["🇬🇧 Quel mot signifie « jaune » ?", "yellow", "purple", "white"],
      ["🇬🇧 Que veut dire « please » ?", "s’il te plaît", "merci", "pardon"],
    ],
    2: [
      ["🇬🇧 Complète : I ___ swim.", "can", "am", "has"],
      ["🇬🇧 Que veut dire « There is a cat » ?", "Il y a un chat", "Voici deux chiens", "Le chat dort"],
      ["🇬🇧 Où est le livre dans « The book is under the table » ?", "sous la table", "sur la table", "dans la table"],
      ["🇬🇧 Comment dit-on 8 h 30 ?", "half past eight", "eight past half", "half to eight"],
      ["🇬🇧 Que veut dire « trousers » ?", "pantalon", "chaussures", "chemise"],
      ["🇬🇧 Complète : She ___ apples.", "likes", "like", "liking"],
      ["🇬🇧 Dans quel pays se trouve London ?", "the United Kingdom", "the United States", "Ireland"],
      ["🇬🇧 Que veut dire « How much is it? » ?", "Combien ça coûte ?", "Quelle heure est-il ?", "Quel âge as-tu ?"],
    ],
    3: [
      ["🇬🇧 Complète : Last week, we ___ a museum.", "visited", "visit", "will visit"],
      ["🇬🇧 Complète : Tomorrow, I ___ my grandmother.", "will see", "saw", "seeing"],
      ["🇬🇧 Complète : A train is ___ than a bicycle.", "faster", "fastest", "more fast"],
      ["🇬🇧 Quel mot interrogatif demande une raison ?", "why", "where", "when"],
      ["🇬🇧 Que veut dire « usually » ?", "d’habitude", "jamais", "hier"],
      ["🇬🇧 Quelle fête est célébrée le 31 octobre ?", "Halloween", "Christmas", "Easter"],
      ["🇬🇧 Complète : They ___ doing their homework.", "are", "is", "am"],
      ["🇬🇧 Que signifie « Could you help me? » ?", "Pourrais-tu m’aider ?", "Veux-tu partir ?", "As-tu terminé ?"],
    ],
  },
  "culture-generale": {
    1: [
      ["🚦 Quelle couleur du feu autorise les voitures à avancer ?", "vert", "rouge", "orange"],
      ["📮 Où dépose-t-on une lettre à envoyer ?", "dans une boîte aux lettres", "dans une poubelle", "dans un cartable"],
      ["🧑‍🚒 Qui intervient pour éteindre un incendie ?", "les pompiers", "les boulangers", "les facteurs"],
      ["🥖 Où achète-t-on généralement du pain ?", "à la boulangerie", "à la bibliothèque", "à la mairie"],
      ["🦒 Quel animal possède un très long cou ?", "la girafe", "le hérisson", "le dauphin"],
      ["🗓️ Quel jour vient après vendredi ?", "samedi", "jeudi", "lundi"],
      ["♻️ Dans quel bac place-t-on souvent le papier recyclable ?", "le bac de tri", "le lavabo", "le coffre à jouets"],
      ["🩹 Qui soigne les personnes malades ?", "un médecin", "un pilote", "un peintre"],
    ],
    2: [
      ["🧭 Quel instrument indique le nord ?", "une boussole", "un thermomètre", "une balance"],
      ["✈️ Qui a réalisé l’un des premiers vols motorisés contrôlés ?", "les frères Wright", "les frères Lumière", "les frères Grimm"],
      ["🗽 Dans quelle ville se trouve la statue de la Liberté ?", "New York", "Madrid", "Tokyo"],
      ["🏅 Combien d’anneaux comporte le symbole olympique ?", "5", "4", "6"],
      ["🎬 Quel appareil sert à filmer des images ?", "une caméra", "une boussole", "un stéthoscope"],
      ["📰 Quel média publie des articles d’actualité ?", "un journal", "un dictionnaire", "un calendrier"],
      ["🌋 Comment appelle-t-on une montagne qui peut rejeter de la lave ?", "un volcan", "un glacier", "un plateau"],
      ["🧪 Où un scientifique mène-t-il souvent ses expériences ?", "dans un laboratoire", "dans un tribunal", "dans un théâtre"],
    ],
    3: [
      ["📖 Qui a écrit « Le Petit Prince » ?", "Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo"],
      ["🏛️ Où siège l’Assemblée nationale française ?", "au palais Bourbon", "au château de Versailles", "au palais des Papes"],
      ["🌐 Que signifie l’abréviation WWW ?", "World Wide Web", "World Writing Word", "Wide World Wire"],
      ["🧬 Quelle molécule porte l’information génétique ?", "l’ADN", "l’eau", "l’oxygène"],
      ["🌍 Quel continent compte le plus de pays ?", "l’Afrique", "l’Europe", "l’Océanie"],
      ["📰 Pourquoi faut-il vérifier la source d’une information ?", "pour évaluer sa fiabilité", "pour la rendre plus longue", "pour éviter de la lire"],
      ["🏆 Quel prix récompense notamment des travaux scientifiques et la paix ?", "le prix Nobel", "le prix Goncourt", "la Palme d’or"],
      ["🔐 Quel mot de passe est le plus sûr ?", "une longue phrase unique", "123456", "son prénom"],
    ],
  },
  sciences: {
    1: [
      ["🪵 Le bois est-il solide ou liquide ?", "solide", "liquide", "gazeux"],
      ["🌞 Qu’est-ce qui alterne avec la nuit ?", "le jour", "l’hiver", "la pluie"],
      ["🐶 De quoi un animal a-t-il besoin pour vivre ?", "d’eau et de nourriture", "de peinture", "de plastique"],
      ["✂️ Quel objet sert à découper du papier ?", "des ciseaux", "une règle", "une gomme"],
      ["🧼 Pourquoi se lave-t-on les mains ?", "pour enlever des microbes", "pour mieux entendre", "pour grandir plus vite"],
      ["🌸 Quelle saison vient après l’hiver ?", "le printemps", "l’automne", "l’été"],
      ["♻️ Que peut-on faire d’un objet encore utilisable ?", "le réemployer", "le jeter dans la nature", "le brûler"],
      ["🔦 Où se forme l’ombre d’un objet éclairé ?", "du côté opposé à la lumière", "dans la lampe", "toujours au-dessus"],
    ],
    2: [
      ["💧 Que devient l’eau liquide lorsqu’elle s’évapore ?", "de la vapeur d’eau", "de la glace", "du sable"],
      ["🌿 Dans une chaîne alimentaire, qui produit sa matière grâce au Soleil ?", "les plantes", "les rochers", "les nuages"],
      ["🧊 À quelle température l’eau pure gèle-t-elle environ ?", "0 °C", "50 °C", "100 °C"],
      ["⚡ Quel geste est dangereux près d’une prise électrique ?", "y introduire un objet", "éteindre la lampe", "appeler un adulte"],
      ["⚙️ À quoi sert un levier ?", "à déplacer plus facilement une charge", "à mesurer la température", "à produire de la pluie"],
      ["🌍 Quel mouvement de la Terre explique le jour et la nuit ?", "sa rotation", "sa fusion", "son évaporation"],
      ["☀️ Quelle énergie est renouvelable ?", "l’énergie solaire", "le charbon", "le pétrole"],
      ["🦔 Qu’est-ce qu’un habitat pour un animal ?", "son milieu de vie", "sa nourriture seulement", "la couleur de son corps"],
    ],
    3: [
      ["🔋 Quelle forme d’énergie une pile fournit-elle à un circuit ?", "électrique", "nucléaire", "éolienne"],
      ["🏀 Comment appelle-t-on le chemin suivi par un objet en mouvement ?", "sa trajectoire", "sa température", "sa matière"],
      ["💡 Que faut-il pour qu’une ampoule s’allume dans un circuit simple ?", "un circuit fermé", "un fil coupé", "une pile absente"],
      ["🚦 Quel type de signal est un feu rouge ?", "un signal visuel", "un signal gustatif", "un signal tactile"],
      ["🛠️ Pourquoi fabrique-t-on un objet technique ?", "pour répondre à un besoin", "pour changer les saisons", "pour créer un être vivant"],
      ["🌳 Qu’est-ce qu’un écosystème ?", "un milieu et les êtres vivants qui y interagissent", "une seule espèce", "une machine électrique"],
      ["🌡️ Quelle tendance décrit le réchauffement climatique actuel ?", "une hausse durable de la température moyenne", "une nuit plus froide", "une marée quotidienne"],
      ["🚿 Quel geste économise l’eau ?", "fermer le robinet pendant le brossage", "laisser couler l’eau", "prendre deux bains par jour"],
    ],
  },
  "histoire-geographie": {
    1: [
      ["⌛ Quel mot désigne ce qui s’est déjà passé ?", "le passé", "le futur", "demain"],
      ["📅 Dans quel ordre range-t-on les événements sur une frise ?", "du plus ancien au plus récent", "au hasard", "du plus loin au plus proche"],
      ["🗺️ Que représente un plan de quartier ?", "des lieux vus de dessus", "la météo de demain", "une histoire imaginaire"],
      ["🏫 Quel lieu est un service public ?", "une école municipale", "une chambre", "un jardin privé"],
      ["🌾 Quel paysage trouve-t-on souvent à la campagne ?", "des champs", "des gratte-ciel", "des quais de métro"],
      ["🏙️ Où trouve-t-on généralement beaucoup d’immeubles ?", "en ville", "en haute mer", "dans une forêt"],
      ["🧭 Sur une carte, à quoi sert la légende ?", "à expliquer les symboles", "à donner l’heure", "à compter les habitants"],
      ["🏠 Qu’est-ce qu’une adresse permet de repérer ?", "un lieu précis", "une saison", "un métier"],
    ],
    2: [
      ["🪨 Quelle période précède l’invention de l’écriture ?", "la Préhistoire", "le Moyen Âge", "l’époque contemporaine"],
      ["🏺 Quelle civilisation antique a construit de nombreux aqueducs ?", "les Romains", "les Vikings", "les Incas"],
      ["🏰 Quel bâtiment fortifié abritait souvent un seigneur au Moyen Âge ?", "un château fort", "une usine", "une gare"],
      ["🌊 Quel fleuve traverse Paris ?", "la Seine", "la Loire", "le Rhône"],
      ["⛰️ Quel relief est très élevé et pentu ?", "une montagne", "une plaine", "une plage"],
      ["🚜 Quelle activité est fréquente dans un espace rural ?", "l’agriculture", "le métro", "le trafic portuaire"],
      ["🏘️ Qu’est-ce qu’une commune ?", "un territoire administré par une mairie", "un continent", "une chaîne de montagnes"],
      ["🗺️ Quelle ligne imaginaire partage la Terre en deux hémisphères ?", "l’équateur", "le méridien de Paris", "le tropique seulement"],
    ],
    3: [
      ["1789 Quel événement majeur débute en France en 1789 ?", "la Révolution française", "la Première Guerre mondiale", "la Renaissance"],
      ["🇫🇷 Quelle devise figure sur les bâtiments publics français ?", "Liberté, Égalité, Fraternité", "Travail, Famille, Patrie", "Un pour tous"],
      ["🗳️ Dans une démocratie, comment les citoyens choisissent-ils leurs représentants ?", "par le vote", "par tirage sportif", "par héritage"],
      ["🇪🇺 Qu’est-ce que l’Union européenne ?", "une union de pays européens", "un seul pays", "une chaîne de montagnes"],
      ["🌍 Quel océan sépare principalement l’Europe de l’Amérique ?", "l’Atlantique", "le Pacifique", "l’Indien"],
      ["🏭 Qu’est-ce que l’industrialisation ?", "le développement de la production en usine", "le retour à la Préhistoire", "la disparition des villes"],
      ["🚆 Pourquoi les réseaux de transport relient-ils les territoires ?", "pour déplacer personnes et marchandises", "pour arrêter les échanges", "pour modifier le climat"],
      ["🌱 Que cherche un aménagement durable ?", "à concilier besoins humains et environnement", "à consommer sans limite", "à supprimer tous les logements"],
    ],
  },
  logique: {
    1: [
      ["🔢 Complète : 2, 4, 6, __.", "8", "7", "10"],
      ["🔺 Quel motif vient ensuite : rond, carré, rond, carré, __ ?", "rond", "triangle", "carré"],
      ["📏 Tom est plus grand que Léa. Qui est la plus petite ?", "Léa", "Tom", "on ne peut pas savoir"],
      ["➡️ Tu avances de deux cases depuis la case 3. Où arrives-tu ?", "5", "4", "6"],
      ["🐘 Quel élément n’appartient pas au groupe : chat, chien, éléphant, table ?", "table", "éléphant", "chien"],
      ["🧩 Si toutes les étoiles sont jaunes et que ceci est une étoile, elle est…", "jaune", "bleue", "invisible"],
      ["📦 La balle est dans la boîte. Où est-elle ?", "à l’intérieur", "derrière", "au-dessus"],
      ["🔢 Quel nombre manque : 10, 9, __, 7 ?", "8", "6", "11"],
    ],
    2: [
      ["🔢 Complète : 3, 6, 9, 12, __.", "15", "14", "18"],
      ["🔐 Dans un code, A=1, B=2, C=3. Quel nombre représente C ?", "3", "2", "4"],
      ["🧺 Quel intrus : pomme, poire, carotte, banane ?", "carotte", "poire", "banane"],
      ["🕒 Un film commence à 14 h et dure 2 h. Quand finit-il ?", "16 h", "15 h", "17 h"],
      ["🧩 Si aucun poisson ne marche et que Nemo est un poisson, Nemo peut-il marcher ?", "non", "oui", "seulement le matin"],
      ["↗️ Depuis une case, tu vas d’une case à droite puis une en haut. Quel déplacement as-tu fait ?", "une diagonale vers le haut à droite", "deux cases à gauche", "une case en bas"],
      ["🔢 Quel nombre ne suit pas la règle : 5, 10, 15, 22, 25 ?", "22", "15", "25"],
      ["⚖️ Deux pommes pèsent autant que quatre prunes. Une pomme pèse autant que…", "deux prunes", "quatre prunes", "une demi-prune"],
    ],
    3: [
      ["🔢 Complète : 1, 4, 9, 16, __.", "25", "20", "24"],
      ["🧭 Sur une grille, partir de (2;3) et avancer de 2 vers la droite donne…", "(4;3)", "(2;5)", "(0;3)"],
      ["🍰 Une recette pour 4 personnes utilise 2 œufs. Pour 8 personnes, il faut…", "4 œufs", "6 œufs", "8 œufs"],
      ["🕒 Un train part à 9 h 45 et roule 1 h 30. Il arrive à…", "11 h 15", "10 h 75", "11 h 30"],
      ["🧩 Tous les carrés sont des rectangles. Cette figure est un carré, donc…", "c’est aussi un rectangle", "ce n’est jamais un rectangle", "c’est forcément un cercle"],
      ["🔐 Si CHAT devient DIBU en avançant chaque lettre d’un rang, CHIEN commence par…", "D", "B", "E"],
      ["📊 Dans une classe, 12 élèves aiment lire et 8 préfèrent dessiner. Combien sont cités ?", "20", "4", "96"],
      ["🔢 Quel terme vient ensuite : 2, 3, 5, 8, 13, __ ?", "21", "18", "26"],
    ],
  },
  orthographe: {
    1: [
      ["🔤 Quelle lettre complète « _ateau » ?", "g", "j", "q"],
      ["🔤 Quel mot commence par le son [ch] ?", "chat", "gare", "rose"],
      ["✍️ Quelle phrase commence correctement ?", "Le chien court.", "le chien court.", "Le chien court"],
      ["🔡 Quel mot est correctement écrit ?", "école", "ékole", "écolle"],
      ["👧 Complète : une fille gentil__.", "le", "s", "x"],
      ["🐱 Complète : des chat__.", "s", "x", "z"],
      ["❓ Quel signe termine une question ?", "?", ".", ","],
      ["🔤 Dans quel ordre alphabétique viennent ces mots ?", "arbre, bateau, chat", "chat, arbre, bateau", "bateau, chat, arbre"],
    ],
    2: [
      ["✍️ Complète : Paul ___ un vélo.", "a", "à", "as"],
      ["✍️ Complète : Il va ___ l’école.", "à", "a", "as"],
      ["✍️ Complète : Léa ___ Hugo jouent.", "et", "est", "ai"],
      ["✍️ Complète : Le chat ___ noir.", "est", "et", "es"],
      ["👧 Choisis le groupe nominal correct.", "les petites maisons", "les petite maisons", "les petites maison"],
      ["⏳ Complète au présent : Nous ___ nos devoirs.", "faisons", "fait", "ferons"],
      ["⏳ Complète à l’imparfait : Il ___ souvent ici.", "venait", "viendra", "vient"],
      ["🔤 Quel mot appartient à la famille de « chant » ?", "chanteur", "champ", "chance"],
    ],
    3: [
      ["✍️ Complète : ___ amis arrivent.", "Ses", "Ces", "C’est"],
      ["✍️ Complète : ___ une belle journée.", "C’est", "Ses", "Sait"],
      ["✍️ Complète : Ils ___ terminé.", "ont", "on", "ons"],
      ["✍️ Complète : ___ écoute attentivement.", "On", "Ont", "Hont"],
      ["👧 Choisis l’accord correct.", "des histoires passionnantes", "des histoire passionnante", "des histoires passionnant"],
      ["⏳ Complète au futur : Demain, nous ___ tôt.", "partirons", "partions", "partons"],
      ["🔤 Quel mot est formé avec un préfixe ?", "impossible", "maison", "soleil"],
      ["✍️ Quel participe passé est correct avec « elles sont » ?", "arrivées", "arrivé", "arrivés"],
    ],
  },
  arts: {
    1: [
      ["🎨 Que donne le mélange du bleu et du jaune ?", "du vert", "du rouge", "du violet"],
      ["🖍️ Quel outil peut tracer au graphite ?", "un crayon à papier", "un pinceau", "une éponge"],
      ["🧱 Quel matériau peut-on modeler avec les mains ?", "l’argile", "le verre", "le marbre"],
      ["🎵 Que peut-on frapper pour produire un rythme ?", "un tambour", "une feuille de papier immobile", "une photographie"],
      ["🎤 Comment appelle-t-on une chanson chantée par une seule personne ?", "un solo", "un duo", "un chœur"],
      ["🖼️ Qu’est-ce qu’un portrait ?", "la représentation d’une personne", "un paysage seulement", "une carte routière"],
      ["📐 Quelle forme n’a aucun côté ?", "le cercle", "le carré", "le triangle"],
      ["🎶 Un son fort et un son doux diffèrent par…", "leur intensité", "leur couleur", "leur forme"],
    ],
    2: [
      ["🖼️ Dans une image, qu’est-ce que le premier plan ?", "la zone qui paraît la plus proche", "le cadre", "la zone la plus sombre"],
      ["🎨 Que permet un contraste clair-foncé ?", "de faire ressortir des formes", "d’effacer toutes les couleurs", "de rendre le papier plus épais"],
      ["🎵 Qu’est-ce que le timbre d’un instrument ?", "sa couleur sonore", "sa taille", "son prix"],
      ["🎼 Que signifie « crescendo » ?", "jouer de plus en plus fort", "jouer de plus en plus lentement", "s’arrêter"],
      ["🧩 Qu’est-ce qu’un collage ?", "une œuvre assemblant des éléments collés", "une sculpture en pierre", "une chanson sans paroles"],
      ["📸 Quel cadrage montre un détail de très près ?", "un gros plan", "un plan général", "une vue aérienne"],
      ["🎭 À quoi sert un décor de théâtre ?", "à représenter le lieu de l’action", "à remplacer les acteurs", "à écrire la musique"],
      ["🎶 Dans une chanson, qu’est-ce qu’un refrain ?", "une partie qui revient", "la dernière note seulement", "le nom du chanteur"],
    ],
    3: [
      ["🎨 Quel mouvement artistique fragmente souvent les formes en volumes géométriques ?", "le cubisme", "l’impressionnisme", "le romantisme"],
      ["🖼️ Qu’est-ce qu’une nature morte ?", "la représentation d’objets inanimés", "un autoportrait", "une scène sportive"],
      ["🎬 Que produit le montage au cinéma ?", "l’enchaînement organisé des plans", "la fabrication de la caméra", "le maquillage des acteurs"],
      ["🏛️ Qu’est-ce qu’une installation artistique ?", "une œuvre organisée dans un espace", "une chanson à deux voix", "un dessin minuscule"],
      ["🎵 Qu’est-ce qu’une polyphonie ?", "plusieurs voix ou lignes musicales simultanées", "un seul son répété", "une musique sans rythme"],
      ["📐 À quoi sert la perspective dans une image ?", "à suggérer la profondeur", "à supprimer les formes", "à mesurer le son"],
      ["🖌️ Quel artiste est associé aux Nymphéas ?", "Claude Monet", "Pablo Picasso", "Auguste Rodin"],
      ["💻 Qu’est-ce qu’une œuvre numérique ?", "une œuvre créée ou présentée avec des outils numériques", "une œuvre sans image", "une œuvre obligatoirement ancienne"],
    ],
  },
};
