// Contenus relus manuellement, organisés par matière et niveau de difficulté.
// Chaque entrée contient : question, bonne réponse, deux distracteurs.
export const SUPPLEMENTAL_SUBJECT_FACTS = {
  sciences: {
    1: [
      ["🌱 Quelle partie de la plante absorbe l’eau du sol ?", "les racines", "les fleurs", "les fruits"],
      ["🐸 Dans quel milieu une grenouille peut-elle vivre ?", "dans l’eau et sur terre", "seulement dans le désert", "seulement dans les arbres"],
      ["☀️ Quelle étoile éclaire la Terre ?", "le Soleil", "la Lune", "Mars"],
      ["🐣 Comment appelle-t-on le petit de la poule ?", "le poussin", "le veau", "le têtard"],
      ["🍂 À quelle saison les feuilles tombent-elles souvent ?", "en automne", "au printemps", "en été"],
    ],
    2: [
      ["🌧️ Comment appelle-t-on l’eau qui tombe des nuages ?", "les précipitations", "la germination", "la respiration"],
      ["🌿 Quel être vivant produit sa nourriture grâce à la lumière ?", "une plante verte", "un caillou", "un champignon"],
      ["🐛 Que devient généralement une chenille ?", "un papillon", "une grenouille", "un poisson"],
      ["🌍 Combien de temps la Terre met-elle environ pour tourner autour du Soleil ?", "un an", "un jour", "un mois"],
      ["🪐 Quelle planète est célèbre pour ses anneaux ?", "Saturne", "Mercure", "la Terre"],
    ],
    3: [
      ["🌿 Quel processus permet aux plantes de fabriquer leur matière grâce à la lumière ?", "la photosynthèse", "la digestion", "la fusion"],
      ["🍃 Quel gaz les plantes rejettent-elles surtout pendant la photosynthèse ?", "l’oxygène", "l’hélium", "l’azote liquide"],
      ["🌋 Comment appelle-t-on la roche liquide sous la surface terrestre ?", "le magma", "la lave", "le granite"],
      ["🌍 Quelle couche de la Terre est fragmentée en plaques ?", "la lithosphère", "le noyau interne", "l’atmosphère"],
      ["🪐 Quelle est la plus grande planète du système solaire ?", "Jupiter", "Mars", "Vénus"],
    ],
  },
  anglais: {
    1: [
      ["🇬🇧 Que veut dire « green » ?", "vert", "gris", "rose"],
      ["🇬🇧 Quel mot signifie « maman » ?", "mother", "brother", "father"],
      ["🇬🇧 Que veut dire « book » ?", "livre", "cahier", "stylo"],
      ["🇬🇧 Quel mot signifie « quatre » ?", "four", "five", "first"],
      ["🇬🇧 Que veut dire « goodbye » ?", "au revoir", "bonjour", "s’il te plaît"],
    ],
    2: [
      ["🇬🇧 Que veut dire « breakfast » ?", "petit-déjeuner", "déjeuner", "dîner"],
      ["🇬🇧 Complète : I ___ eight years old.", "am", "is", "are"],
      ["🇬🇧 Complète : He ___ my friend.", "is", "am", "are"],
      ["🇬🇧 Quel est le pluriel de « child » ?", "children", "childs", "childes"],
      ["🇬🇧 Que veut dire « cloudy » ?", "nuageux", "ensoleillé", "venteux"],
      ["🇬🇧 Quel mot signifie « mercredi » ?", "Wednesday", "Thursday", "Saturday"],
      ["🇬🇧 Que veut dire « kitchen » ?", "cuisine", "chambre", "jardin"],
      ["🇬🇧 Complète : We ___ football.", "play", "plays", "playing"],
      ["🇬🇧 Quel est le contraire de « big » ?", "small", "long", "high"],
      ["🇬🇧 Que veut dire « always » ?", "toujours", "jamais", "parfois"],
      ["🇬🇧 Choisis la bonne traduction de « J’aime lire ».", "I like reading", "I read like", "I am book"],
    ],
    3: [
      ["🇬🇧 Complète : Yesterday, I ___ to school.", "went", "go", "goed"],
      ["🇬🇧 Quel est le passé de « see » ?", "saw", "seed", "seen yesterday"],
      ["🇬🇧 Que signifie « I have already finished » ?", "J’ai déjà terminé", "Je vais commencer", "Je n’ai jamais fini"],
      ["🇬🇧 Complète : If it rains, we ___ inside.", "will stay", "stayed yesterday", "stays"],
      ["🇬🇧 Quel mot signifie « environnement » ?", "environment", "government", "development"],
      ["🇬🇧 Choisis la phrase correcte.", "She doesn’t like carrots.", "She don’t likes carrots.", "She not like carrots."],
      ["🇬🇧 Que veut dire « although » ?", "bien que", "parce que", "ensuite"],
      ["🇬🇧 Complète : This book is ___ than that one.", "more interesting", "interestinger", "most interesting"],
      ["🇬🇧 Quel est le superlatif de « good » ?", "the best", "the goodest", "the better"],
      ["🇬🇧 Que signifie « How long have you lived here? » ?", "Depuis combien de temps vis-tu ici ?", "Où vas-tu habiter ?", "Quelle est ta maison ?"],
      ["🇬🇧 Complète : The cake ___ by Tom.", "was made", "made", "was make"],
    ],
  },
  "culture-generale": {
    1: [
      ["🐘 Quel animal possède une trompe ?", "l’éléphant", "le lion", "le zèbre"],
      ["🗓️ Combien de mois compte une année ?", "12", "10", "14"],
      ["🚦 Quelle couleur du feu signifie qu’il faut s’arrêter ?", "rouge", "verte", "bleue"],
      ["🧀 Quel aliment est fabriqué avec du lait ?", "le fromage", "le pain", "le riz"],
      ["🏥 Où soigne-t-on les personnes malades ?", "à l’hôpital", "à la gare", "au musée"],
    ],
    2: [
      ["🌍 Quel pays a la forme d’une botte ?", "l’Italie", "la Belgique", "le Portugal"],
      ["🗽 Dans quelle ville se trouve la statue de la Liberté ?", "New York", "Paris", "Tokyo"],
      ["🐧 Sur quel continent vivent naturellement les manchots empereurs ?", "l’Antarctique", "l’Europe", "l’Asie"],
      ["🎭 Dans quel bâtiment assiste-t-on à une pièce jouée sur scène ?", "un théâtre", "une usine", "une mairie"],
      ["🧭 Quel instrument indique le nord ?", "une boussole", "un thermomètre", "une balance"],
      ["✉️ Quel service transporte les lettres ?", "la poste", "la police", "la bibliothèque"],
      ["🌋 Comment appelle-t-on une montagne qui peut rejeter de la lave ?", "un volcan", "un glacier", "un canyon"],
      ["🎹 Qui compose une œuvre musicale ?", "un compositeur", "un architecte", "un astronome"],
      ["🐪 Quel animal est adapté aux déplacements dans le désert ?", "le dromadaire", "le pingouin", "la baleine"],
      ["📰 Comment appelle-t-on une personne qui collecte et vérifie des informations ?", "un journaliste", "un boulanger", "un pilote"],
      ["🏅 À quelle fréquence ont lieu normalement les Jeux olympiques d’été ?", "tous les 4 ans", "tous les ans", "tous les 10 ans"],
    ],
    3: [
      ["📖 Qui a écrit « Le Petit Prince » ?", "Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo"],
      ["🔬 Quel scientifique est associé à la théorie de la relativité ?", "Albert Einstein", "Louis Pasteur", "Galilée"],
      ["🌐 Que signifient les lettres WWW ?", "World Wide Web", "World Written Word", "Wide World Wire"],
      ["🏛️ Dans quel pays la démocratie antique s’est-elle développée ?", "la Grèce", "le Canada", "l’Australie"],
      ["🎨 Dans quel musée parisien peut-on voir La Joconde ?", "le Louvre", "Orsay", "le Prado"],
      ["💶 Combien de pays utilisent environ l’euro comme monnaie officielle ?", "une vingtaine", "deux", "plus de cent"],
      ["🌊 Quel canal relie la mer Méditerranée à la mer Rouge ?", "le canal de Suez", "le canal du Midi", "le canal de Panama"],
      ["🧬 Que contient principalement l’ADN ?", "l’information génétique", "de l’air", "de la lumière"],
      ["📡 À quoi sert un satellite de télécommunication ?", "à transmettre des signaux", "à fabriquer de l’eau", "à arrêter le vent"],
      ["🏆 Quel prix récompense notamment des avancées scientifiques et la paix ?", "le prix Nobel", "le César", "le Tour de France"],
      ["🌳 Quelle forêt est la plus vaste forêt tropicale du monde ?", "l’Amazonie", "la forêt de Brocéliande", "la taïga française"],
    ],
  },
  "histoire-geographie": {
    1: [
      ["🗺️ Quelle couleur représente souvent la mer sur une carte ?", "bleu", "rouge", "orange"],
      ["🏙️ Quelle est la capitale de la France ?", "Paris", "Nice", "Bordeaux"],
      ["🏔️ Comment appelle-t-on un relief très élevé ?", "une montagne", "une plaine", "une plage"],
      ["⌛ Ce qui s’est passé avant aujourd’hui appartient…", "au passé", "au futur", "à demain"],
      ["🌍 Combien la Terre compte-t-elle de continents selon le découpage scolaire français ?", "6", "4", "9"],
    ],
    2: [
      ["🏺 Quelle période précède l’Antiquité ?", "la Préhistoire", "le Moyen Âge", "l’époque contemporaine"],
      ["👑 Comment s’appelait le roi surnommé le Roi-Soleil ?", "Louis XIV", "François Ier", "Louis XVI"],
      ["🛡️ Quel peuple vivait en Gaule avant la conquête romaine ?", "les Gaulois", "les Incas", "les Samouraïs"],
      ["⛪ Quel bâtiment est au centre de nombreux villages médiévaux ?", "l’église", "l’aéroport", "le gratte-ciel"],
      ["🏞️ Quel est le plus long fleuve de France ?", "la Loire", "la Seine", "la Garonne"],
      ["🏔️ Quelle chaîne de montagnes borde le sud-est de la France ?", "les Alpes", "les Andes", "l’Oural"],
      ["🌊 Quelle mer borde le sud de la France ?", "la Méditerranée", "la mer Baltique", "la mer Noire"],
      ["🗺️ Qu’indique la légende d’une carte ?", "la signification des symboles", "l’âge de la carte", "le prix du papier"],
      ["🏙️ Une zone très peuplée organisée autour d’une grande ville est…", "une aire urbaine", "un océan", "un volcan"],
      ["🚜 Quel espace est principalement consacré aux champs et à l’élevage ?", "l’espace rural", "le centre-ville", "le port"],
      ["🌍 Quel océan borde l’ouest de la France ?", "l’océan Atlantique", "l’océan Indien", "l’océan Pacifique"],
    ],
    3: [
      ["⚔️ En quelle année débute la Première Guerre mondiale ?", "1914", "1789", "1939"],
      ["🕊️ En quelle année se termine la Seconde Guerre mondiale en Europe ?", "1945", "1918", "1968"],
      ["🇫🇷 Qui lance l’appel du 18 juin 1940 ?", "Charles de Gaulle", "Napoléon Ier", "Louis XIV"],
      ["🏭 Quel grand changement économique débute au XIXe siècle ?", "la révolution industrielle", "la Préhistoire", "la féodalité"],
      ["🗳️ En quelle année les femmes votent-elles pour la première fois en France ?", "1945", "1789", "2002"],
      ["🏛️ Quel pouvoir vote les lois en France ?", "le Parlement", "les musées", "les tribunaux sportifs"],
      ["🌍 Quelle ligne imaginaire partage la Terre en deux hémisphères ?", "l’équateur", "le méridien de Paris", "le tropique polaire"],
      ["🕐 À quoi servent les fuseaux horaires ?", "à organiser l’heure selon les régions du monde", "à mesurer les montagnes", "à prévoir les séismes"],
      ["🏙️ Comment appelle-t-on le déplacement des habitants vers les villes ?", "l’urbanisation", "l’évaporation", "la colonisation végétale"],
      ["🌱 Qu’est-ce que le développement durable cherche à concilier ?", "économie, société et environnement", "sport et musique", "passé et futur uniquement"],
      ["🇪🇺 Quel ensemble politique et économique réunit la France et d’autres pays européens ?", "l’Union européenne", "l’Union africaine", "l’ASEAN"],
    ],
  },
  logique: {
    1: [
      ["🧩 Complète : 5, 10, 15, …", "20", "16", "25"],
      ["🔎 Trouve l’intrus : carré, triangle, carotte.", "carotte", "carré", "triangle"],
      ["🧠 Si Mia est derrière Léo, qui est devant ?", "Léo", "Mia", "on ne sait pas"],
      ["🔢 Quel nombre manque : 1, 2, …, 4 ?", "3", "5", "0"],
      ["🟡 Complète : jaune, vert, jaune, vert, …", "jaune", "rouge", "bleu"],
    ],
    2: [
      ["🧩 Complète : 2, 5, 8, 11, …", "14", "13", "15"],
      ["🔢 Quel nombre est à la fois pair et supérieur à 10 ?", "12", "9", "7"],
      ["🧠 Tous les chats sont des animaux. Mimi est un chat. Mimi est donc…", "un animal", "une plante", "un objet"],
      ["🔎 Trouve l’intrus : 3, 6, 9, 11, 12.", "11", "9", "12"],
      ["🧩 Complète : 100, 90, 80, …", "70", "75", "60"],
      ["🧠 Paul est plus jeune que Lina. Lina est plus jeune que Sami. Qui est le plus âgé ?", "Sami", "Paul", "Lina"],
      ["🔢 Je double un nombre et j’obtiens 18. Quel est ce nombre ?", "9", "8", "36"],
      ["🔐 Avec A=1 et B=2, combien vaut BAB ?", "212", "121", "221"],
      ["📐 Un carré a 4 côtés. Deux carrés séparés ont combien de côtés en tout ?", "8", "6", "4"],
      ["🧩 Quel nombre complète : 1, 4, 9, 16, … ?", "25", "20", "24"],
      ["🧠 Si aujourd’hui est mardi, quel jour sera après-demain ?", "jeudi", "mercredi", "vendredi"],
    ],
    3: [
      ["🧩 Complète : 2, 3, 5, 8, 12, …", "17", "16", "18"],
      ["🔢 Complète : 81, 27, 9, 3, …", "1", "0", "2"],
      ["🧠 Aucun poisson ne vit hors de l’eau. Nemo est un poisson. Nemo vit donc…", "dans l’eau", "dans le désert", "dans un arbre"],
      ["🔐 Si CHAT devient DIBU en avançant chaque lettre d’un rang, que devient BAC ?", "CBD", "CAB", "ACB"],
      ["🧩 Quel nombre n’appartient pas à la suite : 4, 8, 12, 15, 16 ?", "15", "12", "16"],
      ["🧠 Ana est à gauche de Bilal, qui est à gauche de Chloé. Qui est à droite ?", "Chloé", "Ana", "Bilal"],
      ["🔢 Un nombre augmenté de 7 vaut 23. Quel est ce nombre ?", "16", "30", "14"],
      ["🧩 Complète : A, C, E, G, …", "I", "H", "J"],
      ["⚖️ Trois pommes identiques pèsent 450 g. Une pomme pèse…", "150 g", "100 g", "200 g"],
      ["🕐 Une réunion commence à 14 h et dure 90 minutes. Elle finit à…", "15 h 30", "14 h 90", "16 h 30"],
      ["🧠 Si toutes les roses sont des fleurs, peut-on affirmer que toutes les fleurs sont des roses ?", "non", "oui", "seulement le matin"],
    ],
  },
  orthographe: {
    1: [
      ["✍️ Quel mot est bien écrit ?", "chanson", "chansson", "chançon"],
      ["✍️ Complète : une ___ jaune.", "étoile", "étoiles", "étoille"],
      ["✍️ Quel mot contient le son « ou » ?", "souris", "soleil", "salade"],
      ["✍️ Choisis la bonne phrase.", "Maman prépare le repas.", "maman prépare le repas.", "Maman prépare le repa."],
      ["✍️ Complète : deux petits ___.", "lapins", "lapin", "lapines"],
    ],
    2: [
      ["✍️ Complète : Ils ___ faim.", "ont", "on", "ons"],
      ["✍️ Complète : ___ va au parc.", "On", "Ont", "Ons"],
      ["✍️ Complète : Tu ___ un frère.", "as", "a", "à"],
      ["✍️ Complète : Le chat ___ la souris.", "et", "est", "ai"],
      ["✍️ Complète : Il ___ très rapide.", "est", "et", "es"],
      ["✍️ Quel mot est bien écrit ?", "attention", "atention", "attension"],
      ["✍️ Quel mot prend deux « p » ?", "appeler", "apercevoir", "apaiser"],
      ["✍️ Complète : Les fleurs sont ___.", "belles", "beaux", "belle"],
      ["✍️ Complète : Nous ___ à l’école.", "allons", "alon", "allez"],
      ["✍️ Choisis la phrase correcte.", "Mes amis jouent dehors.", "Mes ami joue dehors.", "Mes amis joues dehors."],
      ["✍️ Quel mot est correctement accentué ?", "forêt", "fôret", "foret"],
    ],
    3: [
      ["✍️ Complète : ___ sont mes livres.", "Ce", "Se", "Ceux"],
      ["✍️ Complète : Elle ___ lève tôt.", "se", "ce", "ceux"],
      ["✍️ Complète : Il faut ___ ranger.", "tout", "tous", "toux"],
      ["✍️ Complète : Ils sont ___ venus.", "tous", "tout", "toux"],
      ["✍️ Choisis la phrase correcte.", "Les lettres que j’ai écrites.", "Les lettres que j’ai écrit.", "Les lettres que j’ai écrits."],
      ["✍️ Complète : Bien qu’il ___ fatigué, il continue.", "soit", "est", "sera"],
      ["✍️ Quel mot est bien écrit ?", "développement", "dévelopement", "développemment"],
      ["✍️ Complète : Je ne sais pas ___ il viendra.", "quand", "quant", "qu’en"],
      ["✍️ Complète : ___ à cette idée, elle est intéressante.", "Quant", "Quand", "Qu’en"],
      ["✍️ Choisis la bonne forme.", "Ils convainquent", "Ils convaincs", "Ils convainques"],
      ["✍️ Quel mot est correctement écrit ?", "accueillir", "acceullir", "acceuillir"],
    ],
  },
  arts: {
    1: [
      ["🎵 Quel instrument souffle-t-on pour produire un son ?", "la flûte", "le tambour", "le piano"],
      ["🎨 Quelle couleur obtient-on avec rouge et blanc ?", "rose", "vert", "marron"],
      ["🖼️ Comment appelle-t-on une image réalisée avec un appareil photo ?", "une photographie", "une sculpture", "une chanson"],
      ["🎭 Qui joue un personnage sur scène ?", "un comédien", "un chef d’orchestre", "un peintre"],
      ["🎶 Comment appelle-t-on un groupe de personnes qui chantent ensemble ?", "une chorale", "un musée", "un atelier"],
    ],
    2: [
      ["🎼 Comment appelle-t-on une suite organisée de sons ?", "une mélodie", "une couleur", "une statue"],
      ["🥁 À quelle famille appartient le tambour ?", "les percussions", "les cordes", "les vents"],
      ["🎷 À quelle famille appartient le saxophone ?", "les vents", "les cordes", "les percussions"],
      ["🖌️ Qu’est-ce qu’une palette pour un peintre ?", "un support pour mélanger les couleurs", "un instrument à cordes", "un cadre"],
      ["🖼️ Comment appelle-t-on une peinture représentant une personne ?", "un portrait", "un paysage", "une nature morte"],
      ["🏞️ Une œuvre qui représente principalement la nature est…", "un paysage", "un portrait", "un rythme"],
      ["🍎 Une peinture d’objets immobiles est…", "une nature morte", "une fresque historique", "une danse"],
      ["🎭 Quel texte indique les paroles et les actions d’une pièce ?", "le script", "la partition", "la palette"],
      ["🎶 Quel signe indique un silence en musique ?", "une pause", "une clé", "une gamme"],
      ["🎻 Quel musicien dirige un orchestre ?", "le chef d’orchestre", "le soliste de peinture", "le décorateur sonore"],
      ["🧱 Comment appelle-t-on une œuvre faite de petits morceaux assemblés ?", "une mosaïque", "une symphonie", "une photographie"],
    ],
    3: [
      ["🎨 Quel artiste est associé au cubisme ?", "Pablo Picasso", "Claude Monet", "Auguste Rodin"],
      ["🌻 Qui a peint de célèbres tableaux de tournesols ?", "Vincent van Gogh", "Mozart", "Victor Hugo"],
      ["🗿 Qui a sculpté « Le Penseur » ?", "Auguste Rodin", "Claude Debussy", "Henri Matisse"],
      ["🎼 Qui a composé « La Flûte enchantée » ?", "Mozart", "Beethoven", "Vivaldi"],
      ["🎵 Comment appelle-t-on une œuvre musicale pour orchestre en plusieurs mouvements ?", "une symphonie", "un portrait", "une fable"],
      ["🎨 Quelle technique consiste à coller différents matériaux sur un support ?", "le collage", "la gravure", "l’aquarelle"],
      ["🖌️ Quelle peinture utilise des pigments dilués dans l’eau et joue sur la transparence ?", "l’aquarelle", "la peinture à l’huile", "le fusain"],
      ["🎭 Dans le théâtre, qu’est-ce qu’une didascalie ?", "une indication de mise en scène", "une chanson finale", "le nom du public"],
      ["🎬 Qui coordonne la création artistique d’un film ?", "le réalisateur", "le spectateur", "le libraire"],
      ["🏛️ Quel mouvement artistique recherche l’équilibre inspiré de l’Antiquité ?", "le classicisme", "le cubisme", "le surréalisme"],
      ["🎶 Que mesure le tempo d’une musique ?", "sa vitesse", "sa hauteur", "son auteur"],
    ],
  },
};
